# Generated by Django 5.1.5 on 2026-04-06 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_color", models.CharField(default="#1A73E8", max_length=20)),
                ("secondary_color", models.CharField(default="#5F6368", max_length=20)),
                ("accent_color", models.CharField(default="#1A73E8", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("text_color", models.CharField(default="#20190D", max_length=20)),
                ("logo_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "favicon_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Inter, system-ui, sans-serif", max_length=200
                    ),
                ),
                ("button_radius", models.FloatField(default=4.0)),
                ("custom_css", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "themes",
                "ordering": ["organization__name"],
            },
        ),
    ]
