# Generated by Django 5.1.5 on 2026-04-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="accent_foreground_color",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="border_color",
            field=models.CharField(default="#E2E8F0", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="card_color",
            field=models.CharField(default="#FFFFFF", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="card_foreground_color",
            field=models.CharField(default="#0F172A", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="destructive_color",
            field=models.CharField(default="#EF4444", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="destructive_foreground_color",
            field=models.CharField(default="#FFFFFF", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="muted_color",
            field=models.CharField(default="#F1F5F9", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="muted_foreground_color",
            field=models.CharField(default="#64748B", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="primary_foreground_color",
            field=models.CharField(default="#FFFFFF", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="secondary_foreground_color",
            field=models.CharField(default="#0F172A", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="success_color",
            field=models.CharField(default="#22C55E", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent_color",
            field=models.CharField(default="#F59E0B", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="secondary_color",
            field=models.CharField(default="#F1F5F9", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="text_color",
            field=models.CharField(default="#0F172A", max_length=20),
        ),
    ]
