# Generated by Django 5.1.5 on 2026-04-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0002_theme_accent_foreground_color_theme_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="accent_color_dark",
            field=models.CharField(default="38 92 50", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="accent_foreground_color_dark",
            field=models.CharField(default="0 0 0", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="background_color_dark",
            field=models.CharField(default="222 84 5", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="border_color_dark",
            field=models.CharField(default="217 33 17", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="card_color_dark",
            field=models.CharField(default="222 84 5", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="card_foreground_color_dark",
            field=models.CharField(default="210 40 96", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="custom_css_dark",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="theme",
            name="destructive_color_dark",
            field=models.CharField(default="0 63 31", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="destructive_foreground_color_dark",
            field=models.CharField(default="0 0 100", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="logo_url_dark",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="theme",
            name="muted_color_dark",
            field=models.CharField(default="217 33 17", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="muted_foreground_color_dark",
            field=models.CharField(default="215 20 65", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="primary_color_dark",
            field=models.CharField(default="160 84 39", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="primary_foreground_color_dark",
            field=models.CharField(default="0 0 100", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="secondary_color_dark",
            field=models.CharField(default="210 40 16", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="secondary_foreground_color_dark",
            field=models.CharField(default="210 40 96", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="success_color_dark",
            field=models.CharField(default="142 76 36", max_length=20),
        ),
        migrations.AddField(
            model_name="theme",
            name="text_color_dark",
            field=models.CharField(default="210 40 96", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent_color",
            field=models.CharField(default="38 92 50", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="accent_foreground_color",
            field=models.CharField(default="0 0 0", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="background_color",
            field=models.CharField(default="0 0 100", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="border_color",
            field=models.CharField(default="214 32 91", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="card_color",
            field=models.CharField(default="0 0 100", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="card_foreground_color",
            field=models.CharField(default="222 84 5", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="destructive_color",
            field=models.CharField(default="0 84 60", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="destructive_foreground_color",
            field=models.CharField(default="0 0 100", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="muted_color",
            field=models.CharField(default="210 40 96", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="muted_foreground_color",
            field=models.CharField(default="215 16 47", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary_color",
            field=models.CharField(default="160 84 39", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary_foreground_color",
            field=models.CharField(default="0 0 100", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="secondary_color",
            field=models.CharField(default="210 40 96", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="secondary_foreground_color",
            field=models.CharField(default="222 47 11", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="success_color",
            field=models.CharField(default="142 76 36", max_length=20),
        ),
        migrations.AlterField(
            model_name="theme",
            name="text_color",
            field=models.CharField(default="222 84 5", max_length=20),
        ),
    ]
