# Generated by Django 5.1.5 on 2026-04-18 13:58

import django.db.models.deletion
import themes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_organizationsettings_organizationterminology_and_more"),
        ("themes", "0003_theme_accent_color_dark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "login_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "login_subtitle",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="160 84 39",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "primary_foreground_color",
                    models.CharField(
                        default="0 0 100",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="210 40 96",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "secondary_foreground_color",
                    models.CharField(
                        default="222 47 11",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="38 92 50",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "accent_foreground_color",
                    models.CharField(
                        default="0 0 0",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "primary_color_dark",
                    models.CharField(
                        default="160 84 39",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "primary_foreground_color_dark",
                    models.CharField(
                        default="0 0 100",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "secondary_color_dark",
                    models.CharField(
                        default="210 40 16",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "secondary_foreground_color_dark",
                    models.CharField(
                        default="210 40 96",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "accent_color_dark",
                    models.CharField(
                        default="38 92 50",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "accent_foreground_color_dark",
                    models.CharField(
                        default="0 0 0",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="0 0 100",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="222 84 5",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "muted_color",
                    models.CharField(
                        default="210 40 96",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "muted_foreground_color",
                    models.CharField(
                        default="215 16 47",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "card_color",
                    models.CharField(
                        default="0 0 100",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "card_foreground_color",
                    models.CharField(
                        default="222 84 5",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "background_color_dark",
                    models.CharField(
                        default="222 84 5",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "text_color_dark",
                    models.CharField(
                        default="210 40 96",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "muted_color_dark",
                    models.CharField(
                        default="217 33 17",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "muted_foreground_color_dark",
                    models.CharField(
                        default="215 20 65",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "card_color_dark",
                    models.CharField(
                        default="222 84 5",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "card_foreground_color_dark",
                    models.CharField(
                        default="210 40 96",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="214 32 91",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "destructive_color",
                    models.CharField(
                        default="0 84 60",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "destructive_foreground_color",
                    models.CharField(
                        default="0 0 100",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "success_color",
                    models.CharField(
                        default="142 76 36",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "border_color_dark",
                    models.CharField(
                        default="217 33 17",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "destructive_color_dark",
                    models.CharField(
                        default="0 63 31",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "destructive_foreground_color_dark",
                    models.CharField(
                        default="0 0 100",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                (
                    "success_color_dark",
                    models.CharField(
                        default="142 76 36",
                        max_length=20,
                        validators=[themes.models.validate_hsl_triplet],
                    ),
                ),
                ("logo_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "logo_url_dark",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "favicon_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Inter, system-ui, sans-serif", max_length=200
                    ),
                ),
                ("button_radius", models.FloatField(default=4.0)),
                ("custom_css", models.TextField(blank=True, default="")),
                ("custom_css_dark", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_themes",
                "ordering": ["organization__name"],
            },
        ),
        migrations.DeleteModel(
            name="Theme",
        ),
    ]
