# Generated by Django 5.1.5 on 2026-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_customrole_organizationmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="current_organisation_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="is_lead_assessor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="specializations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
