# Generated by Django 5.1.5 on 2026-04-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0004_organizationmembership_current_organisation_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customrole",
            options={
                "verbose_name": "Custom Role",
                "verbose_name_plural": "Custom Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
            },
        ),
    ]
