# Generated by Django 5.1.5 on 2026-04-11 07:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_customrole_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationCreationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "require_contract_upload",
                    models.BooleanField(
                        default=False,
                        help_text="Require signed contract document before creating organizations",
                    ),
                ),
                (
                    "require_client_email",
                    models.BooleanField(
                        default=True,
                        help_text="Require client admin email for automatic invitation",
                    ),
                ),
                (
                    "require_framework_selection",
                    models.BooleanField(
                        default=True,
                        help_text="Require primary framework selection during creation",
                    ),
                ),
                (
                    "require_industry_sector",
                    models.BooleanField(
                        default=True, help_text="Require industry sector selection"
                    ),
                ),
                (
                    "auto_send_invitation",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically send invitation email after organization creation",
                    ),
                ),
                (
                    "invitation_expiry_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Number of days before invitation links expire",
                    ),
                ),
                (
                    "allowed_creator_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles allowed to create organizations, e.g., ['SUPERADMIN', 'CONSULTANCY_ADMIN']",
                    ),
                ),
                (
                    "helper_title",
                    models.CharField(
                        default="Create New Organization",
                        help_text="Title shown in the creation form",
                        max_length=200,
                    ),
                ),
                (
                    "helper_description",
                    models.TextField(
                        blank=True,
                        default="Set up a new client organization. They will receive an invitation to join Veris.",
                        help_text="Description/helper text shown to users",
                    ),
                ),
                (
                    "prerequisite_warning",
                    models.TextField(
                        blank=True,
                        default="Please ensure you have a signed contract before creating a new organization.",
                        help_text="Warning shown when prerequisites are not met",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Creation Configuration",
                "verbose_name_plural": "Organization Creation Configurations",
                "db_table": "organization_creation_configs",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "fallback_role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("COORDINATOR", "Coordinator"),
                            ("OPERATOR", "Operator"),
                            ("EXECUTIVE", "Executive"),
                            ("ASSESSOR", "Assessor"),
                            ("CONSULTANT", "Consultant"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.customrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "db_table": "invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
