# Generated by Django 5.1.5 on 2026-04-18 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organizationcreationconfig_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("features", models.JSONField(blank=True, default=dict)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
                "db_table": "organization_settings",
            },
        ),
        migrations.CreateModel(
            name="OrganizationTerminology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_label",
                    models.CharField(default="Assessment", max_length=100),
                ),
                ("site_label", models.CharField(default="Site", max_length=100)),
                ("task_label", models.CharField(default="Task", max_length=100)),
                (
                    "evidence_label",
                    models.CharField(default="Evidence", max_length=100),
                ),
                ("report_label", models.CharField(default="Report", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Terminology",
                "verbose_name_plural": "Organization Terminology",
                "db_table": "organization_terminology",
            },
        ),
        migrations.AlterModelOptions(
            name="customrole",
            options={
                "ordering": ["organization__name", "name"],
                "verbose_name": "Custom Role",
                "verbose_name_plural": "Custom Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={
                "ordering": ["organization__name", "user__email"],
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
            },
        ),
        migrations.AlterUniqueTogether(
            name="customrole",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="organizationcreationconfig",
            name="allowed_creator_roles",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="current_organisation_name",
        ),
        migrations.AddField(
            model_name="customrole",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customrole",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customrole",
            name="is_system_role",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customrole",
            name="key",
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organizationcreationconfig",
            name="allow_authenticated_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationcreationconfig",
            name="allow_staff_users",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationcreationconfig",
            name="allow_superusers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INVITED", "Invited"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customrole",
            name="permissions",
            field=models.JSONField(
                default=list,
                help_text="List of permission keys, e.g. ['user:invite', 'report:edit']",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="fallback_role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("COORDINATOR", "Coordinator"),
                    ("OPERATOR", "Operator"),
                    ("EXECUTIVE", "Executive"),
                    ("ASSESSOR", "Assessor"),
                    ("CONSULTANT", "Consultant"),
                ],
                default="OPERATOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to="organizations.customrole",
            ),
        ),
        migrations.AlterField(
            model_name="organizationcreationconfig",
            name="helper_description",
            field=models.TextField(
                blank=True,
                default="Set up a new client organization. They will receive an invitation to join the platform.",
                help_text="Description/helper text shown to users",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="fallback_role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("COORDINATOR", "Coordinator"),
                    ("OPERATOR", "Operator"),
                    ("EXECUTIVE", "Executive"),
                    ("ASSESSOR", "Assessor"),
                    ("CONSULTANT", "Consultant"),
                ],
                default="OPERATOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="organizations.customrole",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customrole",
            unique_together={("organization", "key")},
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("organization", "email", "status"),
                name="unique_pending_invitation_per_org_email",
            ),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationterminology",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminology",
                to="organizations.organization",
            ),
        ),
    ]
