# Generated by Django 5.1.5 on 2026-04-06 11:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("file_url", models.URLField(max_length=1000)),
                ("file_type", models.CharField(default="PDF", max_length=20)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("category", models.CharField(max_length=50)),
                ("embeddings_indexed", models.BooleanField(default=False)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("vector_ids", models.JSONField(default=list)),
                (
                    "framework_tags",
                    models.JSONField(
                        default=list,
                        help_text="Which frameworks this document relates to",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
