# Generated by Django 5.1.5 on 2026-04-06 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("categories", models.JSONField(default=dict)),
                ("scoring_methodology", models.JSONField(default=dict)),
                (
                    "reporting_period",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "frameworks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("questions", models.JSONField(default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="assessments.framework",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_templates",
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("category", models.CharField(blank=True, default="", max_length=200)),
                ("scoring_criteria", models.JSONField(default=dict)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_questions",
                        to="assessments.assessmenttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("due_date", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("overall_score", models.FloatField(default=0.0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="assessments.assessmenttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ESGFocusArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("internal_label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("current_score", models.FloatField(default=0.0)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("UP", "Up"),
                            ("DOWN", "Down"),
                            ("STABLE", "Stable"),
                            ("INSUFFICIENT_DATA", "Insufficient Data"),
                        ],
                        default="INSUFFICIENT_DATA",
                        max_length=30,
                    ),
                ),
                ("last_assessed", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("framework_mappings", models.JSONField(default=dict)),
                ("ai_gaps", models.JSONField(default=dict)),
                ("ai_recommendations", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_areas",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "esg_focus_areas",
                "ordering": ["name"],
                "unique_together": {("organization", "internal_label")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField(blank=True, default="")),
                ("answer_score", models.FloatField(default=0.0)),
                ("evidence_files", models.JSONField(default=list)),
                ("ai_score_suggestion", models.FloatField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True, default="")),
                ("ai_validated", models.BooleanField(default=False)),
                ("frameworks_mapped_to", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="assessments.assessmentquestion",
                    ),
                ),
                (
                    "focus_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="assessments.esgfocusarea",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="focus_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="assessments.esgfocusarea",
            ),
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("GAP_ANALYSIS", "Gap Analysis"),
                            ("RECOMMENDATION", "Recommendation"),
                            ("RISK_FLAG", "Risk Flag"),
                            ("CROSS_FRAMEWAY", "Cross Framework"),
                            ("SUMMARY", "Summary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("insight_text", models.TextField()),
                ("confidence_score", models.FloatField(default=0.0)),
                ("source_documents", models.JSONField(default=list)),
                ("action_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="organizations.organization",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_insights",
                        to="assessments.assessmentresponse",
                    ),
                ),
                (
                    "focus_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_insights",
                        to="assessments.esgfocusarea",
                    ),
                ),
            ],
            options={
                "db_table": "ai_insights",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        choices=[
                            ("MSCI", "MSCI"),
                            ("SUSTAINALYTICS", "Sustainalytics"),
                            ("ISS", "ISS"),
                            ("EQUIABLE_ORIGIN", "Equiable Origin"),
                        ],
                        max_length=30,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("score_date", models.DateField()),
                ("category_scores", models.JSONField(default=dict)),
                (
                    "rating_grade",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("trend_vs_previous", models.FloatField(blank=True, null=True)),
                ("ai_analysis", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ratings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "external_ratings",
                "ordering": ["-score_date"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="assessments.framework",
            ),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OPERATION", "Operation"),
                            ("MINE", "Mine"),
                            ("OFFICE", "Office"),
                            ("FACILITY", "Facility"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country_code", models.CharField(max_length=3)),
                ("region", models.CharField(blank=True, default="", max_length=200)),
                (
                    "coordinates",
                    models.JSONField(
                        default=dict, help_text="{'lat': float, 'lng': float}"
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DECOMMISSIONED", "Decommissioned"),
                            ("PLANNED", "Planned"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("certifications", models.JSONField(default=list)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sites",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="assessments.site",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ai_nudged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "focus_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="assessments.esgfocusarea",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["priority", "due_date"],
            },
        ),
    ]
