# Generated by Django 5.1.5 on 2026-04-06 13:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("organizations", "0002_alter_organization_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="contractor_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="site",
            name="employee_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="site",
            name="estimated_lifetime_years",
            field=models.PositiveIntegerField(
                blank=True, help_text="Remaining operational lifetime", null=True
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="expansion_plan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="site",
            name="industry_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible industry-specific fields. Examples:\n  Coal: type_of_coal, type_of_mine, certifications, contractors, fatalities, etc.\n  Oil/Gas: well_type, production_rate, pipeline_connections, etc.\n  Agriculture: crop_type, hectares, irrigation, etc.\n  Manufacturing: production_lines, capacity, waste_management, etc.",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="is_in_conflict_zone",
            field=models.BooleanField(default=False, help_text="CAHRA or similar"),
        ),
        migrations.AddField(
            model_name="site",
            name="is_in_indigenous_territory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="site",
            name="operational_since",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year operations started", null=True
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="other_certifications",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="site",
            name="risk_profile",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Risk"),
                    ("MEDIUM", "Medium Risk"),
                    ("HIGH", "High Risk"),
                    ("CRITICAL", "Critical Risk"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("PLANNED", "Planned"),
                    ("UNDER_CONSTRUCTION", "Under Construction"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="type",
            field=models.CharField(
                choices=[
                    ("MINE", "Mine"),
                    ("OPERATION", "Oil/Gas Operation"),
                    ("WELL", "Well Pad / Well Site"),
                    ("FACILITY", "Processing Facility"),
                    ("REFINERY", "Refinery"),
                    ("PORT", "Port / Storage Facility"),
                    ("OFFICE", "Regional Office"),
                    ("TRANSPORT", "Transport Infrastructure"),
                    ("FARM", "Farm / Plantation"),
                    ("FACTORY", "Factory / Manufacturing"),
                    ("WAREHOUSE", "Warehouse"),
                    ("RETAIL", "Retail Location"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AssessmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("site_assessment_start", models.DateField()),
                ("site_assessment_end", models.DateField()),
                ("draft_report_deadline", models.DateField()),
                ("final_report_deadline", models.DateField(blank=True, null=True)),
                ("opening_meeting_date", models.DateField(blank=True, null=True)),
                ("closing_meeting_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_plans",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_plans",
                "ordering": ["site_assessment_start"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Assessment Report", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("executive_summary", models.TextField(blank=True, default="")),
                ("methodology", models.TextField(blank=True, default="")),
                ("scope", models.TextField(blank=True, default="")),
                ("country_context", models.TextField(blank=True, default="")),
                ("conclusion", models.TextField(blank=True, default="")),
                ("meeting_participants", models.JSONField(blank=True, default=list)),
                ("stakeholder_meetings", models.JSONField(blank=True, default=list)),
                ("limitations", models.JSONField(blank=True, default=list)),
                ("disclaimer", models.TextField(blank=True, default="")),
                ("assessment_start_date", models.DateField(blank=True, null=True)),
                ("assessment_end_date", models.DateField(blank=True, null=True)),
                ("report_published_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_reports",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CIPCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. '12 Month Review', 'Phase 2'", max_length=100
                    ),
                ),
                (
                    "deadline_period_months",
                    models.PositiveIntegerField(
                        default=12, help_text="Monitoring period in months"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cip_cycles",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cip_cycles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "cip_cycles",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("recommended_actions", models.TextField(blank=True, default="")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("WAIVED", "Waived"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "responsible_party",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("supplier_response", models.TextField(blank=True, default="")),
                ("assessor_comments", models.TextField(blank=True, default="")),
                ("marked_as_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provision",
                    models.ForeignKey(
                        blank=True,
                        help_text="The framework provision this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessments.framework",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assessments.assessmentreport",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="assessments.site",
                    ),
                ),
            ],
            options={
                "db_table": "findings",
                "ordering": ["-severity", "-created_at"],
            },
        ),
    ]
