# Generated by Django 5.1.5 on 2026-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_site_contractor_count_site_employee_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="finding",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
