# Generated by Django 5.1.5 on 2026-04-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentresponse",
            name="citations",
            field=models.JSONField(
                default=list, help_text="Referenced evidence document IDs"
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="confidence_score",
            field=models.FloatField(
                blank=True, help_text="AI confidence 0-1", null=True
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("validated", "Validated"),
                    ("flagged", "Flagged"),
                    ("insufficient_evidence", "Insufficient Evidence"),
                ],
                default="pending",
                max_length=25,
            ),
        ),
    ]
