# Generated by Django 5.1.5 on 2026-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_add_ai_validation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestion",
            name="framework_mappings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
