# Generated by Django 5.1.5 on 2026-04-15 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_add_template_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assessmenttemplate",
            new_name="assessment__is_publ_64df0e_idx",
            old_name="assessments_is_pub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="assessmenttemplate",
            new_name="assessment__owner_o_635e26_idx",
            old_name="assessments_owner_org_status_idx",
        ),
        # Skip AlterUniqueTogether - old 'organization' field was removed in 0007
        migrations.AlterField(
            model_name="assessment",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this assessment was instantiated from a template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="assessments.assessmenttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="assessmenttemplate",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
