# Generated by Django 5.1.5 on 2026-04-15 21:51
# ROBUST FIX: Old unique_together (organization, slug) was removed in 0007.
# Django tries to drop it but fails because 'organization' field doesn't exist.
# We use RunPython to safely check and drop the constraint if it exists.

from django.db import migrations


def drop_old_unique_constraint(apps, schema_editor):
    """
    Safely drop the old unique_together constraint on assessmenttemplate.
    The constraint was on (organization, slug) but organization field was removed.
    We check if it exists first to avoid errors.
    """
    # Table name from model Meta: db_table = "assessment_templates"
    table_name = "assessment_templates"

    with schema_editor.connection.cursor() as cursor:
        # Check for unique constraint on assessment_templates table
        cursor.execute(
            """
            SELECT conname
            FROM pg_constraint
            WHERE conrelid = %s::regclass
            AND contype = 'u'
        """,
            [table_name],
        )
        constraints = [row[0] for row in cursor.fetchall()]

        # Drop any unique constraints that reference 'organization'
        for constraint in constraints:
            if "organization" in constraint.lower() or "org" in constraint.lower():
                try:
                    cursor.execute(
                        f"ALTER TABLE {table_name} DROP CONSTRAINT {constraint}"
                    )
                    print(f"Dropped constraint: {constraint}")
                except Exception as e:
                    print(f"Could not drop {constraint}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0008_rename_assessments_is_pub_status_idx_assessment__is_publ_64df0e_idx_and_more",
        ),
    ]

    operations = [
        # SeparateDatabaseAndState: update Django's model state AND clean up DB
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Tell Django: unique_together is now empty
                migrations.AlterModelOptions(
                    name="assessmenttemplate",
                    options={
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[
                # Use RunPython to safely drop the old constraint
                migrations.RunPython(
                    drop_old_unique_constraint, reverse_code=migrations.RunPython.noop
                ),
            ],
        ),
    ]
