# Generated by Django 5.1.5 on 2026-04-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0012_add_canonical_organization_fields"),
        ("organizations", "0007_organizationsettings_organizationterminology_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmenttemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical tenant organization reference.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_templates",
                to="organizations.organization",
            ),
        ),
    ]
