# Generated by Django 5.1.5 on 2026-04-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0013_alter_assessmenttemplate_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
