# Generated by Django 5.1.5 on 2026-04-27 10:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0014_finding_due_date"),
        ("organizations", "0007_organizationsettings_organizationterminology_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameworkImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("framework_name", models.CharField(max_length=200)),
                ("framework_version", models.CharField(default="1.0.0", max_length=50)),
                ("framework_description", models.TextField(blank=True, default="")),
                ("create_template", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0.0)),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                ("framework_id", models.UUIDField(blank=True, null=True)),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("questions_created", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="framework_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="framework_import_jobs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "framework_import_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
