# Generated by Django 5.1.5 on 2026-04-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0015_frameworkimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
