# Generated by Django 5.1.5 on 2026-04-27 16:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0016_framework_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="assessor_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="assigned_assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assessor_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="assigned_platform_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_platform_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="operator_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="platform_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="review_stage",
            field=models.CharField(
                choices=[
                    ("OPERATOR", "Operator Self-Assessment"),
                    ("PLATFORM", "Platform Review"),
                    ("ASSESSOR", "Assessor Review"),
                    ("COMPLETED", "Completed"),
                ],
                default="OPERATOR",
                help_text="Current stage in multi-party review workflow",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="external_question_id",
            field=models.CharField(
                blank=True,
                help_text="External format: supplement.principle.objective.PT (e.g., '100.1.1.1')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="performance_target_level",
            field=models.IntegerField(
                choices=[
                    (1, "PT1 - Minimum Compliance"),
                    (2, "PT2 - Good Practice"),
                    (3, "PT3 - Best Practice"),
                ],
                default=1,
                help_text="EO100 performance target level",
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessor_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessor_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessor_private_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Private notes - not visible to operator or platform",
            ),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessor_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessor_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="assessor_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="final_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="operator_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="operator_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="operator_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="operator_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="platform_review_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="platform_review_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="platform_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="platform_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="platform_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmenttemplate",
            name="supplement_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEFAULT", "Default"),
                    ("PROCESSING", "Processing"),
                    ("PRODUCTION", "Production"),
                    ("TRANSMISSION_STORAGE", "Transmission & Storage"),
                ],
                help_text="EO100 supplement type (null for non-EO100 frameworks)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Framework-specific metadata (e.g., EO100 supplements, principle count)",
            ),
        ),
        migrations.CreateModel(
            name="SAQToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=10, unique=True)),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_email", models.EmailField(max_length=254)),
                (
                    "site_name",
                    models.CharField(help_text="Mine/site name", max_length=200),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legacy_response_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original cgwg-backend Response.id",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saq_tokens",
                        to="assessments.assessmenttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "saq_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SAQResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "answer_choice",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For Yes/No/NA or select_one questions",
                        max_length=50,
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="For text/short_text questions",
                    ),
                ),
                (
                    "answer_integer",
                    models.IntegerField(
                        blank=True, help_text="For integer questions", null=True
                    ),
                ),
                (
                    "answer_date",
                    models.DateField(
                        blank=True, help_text="For date questions", null=True
                    ),
                ),
                (
                    "answer_multiple",
                    models.JSONField(
                        default=list,
                        help_text="For select_multiple: [choice1, choice2, ...]",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, default="", help_text="Comment box / explanation"
                    ),
                ),
                (
                    "evidence_files",
                    models.JSONField(
                        default=list, help_text="List of uploaded file keys/URLs"
                    ),
                ),
                (
                    "legacy_answer_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original cgwg-backend Answer.id",
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saq_responses",
                        to="assessments.assessmentquestion",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessments.saqtoken",
                    ),
                ),
            ],
            options={
                "db_table": "saq_responses",
                "ordering": ["question__order"],
                "unique_together": {("token", "question")},
            },
        ),
    ]
