# Generated by Django 5.1.5 on 2026-04-29 21:42

import django.db.models.deletion
from django.db import migrations, models


def snapshot_existing_assessment_questions(apps, schema_editor):
    Assessment = apps.get_model("assessments", "Assessment")
    AssessmentQuestion = apps.get_model("assessments", "AssessmentQuestion")
    AssessmentResponse = apps.get_model("assessments", "AssessmentResponse")

    for assessment in Assessment.objects.exclude(template_id__isnull=True):
        if AssessmentQuestion.objects.filter(assessment_id=assessment.id).exists():
            continue

        template_questions = AssessmentQuestion.objects.filter(
            template_id=assessment.template_id,
            assessment_id__isnull=True,
        ).order_by("order")

        for template_question in template_questions:
            snapshot_question = AssessmentQuestion.objects.create(
                template_id=None,
                assessment_id=assessment.id,
                source_template_question_id=template_question.id,
                organization_id=assessment.organization_id,
                text=template_question.text,
                order=template_question.order,
                category=template_question.category,
                scoring_criteria=template_question.scoring_criteria,
                is_required=template_question.is_required,
                performance_target_level=template_question.performance_target_level,
                external_question_id=template_question.external_question_id,
                framework_mappings=template_question.framework_mappings,
            )

            existing_response = AssessmentResponse.objects.filter(
                assessment_id=assessment.id,
                question_id=template_question.id,
            ).first()
            if existing_response:
                existing_response.question_id = snapshot_question.id
                if not existing_response.organization_id:
                    existing_response.organization_id = assessment.organization_id
                existing_response.save(update_fields=["question", "organization"])
            else:
                AssessmentResponse.objects.create(
                    assessment_id=assessment.id,
                    organization_id=assessment.organization_id,
                    question_id=snapshot_question.id,
                    created_by_id=assessment.created_by_id,
                )


def noop_reverse(apps, schema_editor):
    # Snapshot rows preserve audit history; do not delete them on migration rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0017_assessment_assessor_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestion",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for frozen assessment question snapshots.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_questions",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="source_template_question",
            field=models.ForeignKey(
                blank=True,
                help_text="Original template question this snapshot was copied from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_snapshots",
                to="assessments.assessmentquestion",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentquestion",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for reusable template questions. Blank for assessment snapshots.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_questions",
                to="assessments.assessmenttemplate",
            ),
        ),
        migrations.RunPython(
            snapshot_existing_assessment_questions,
            reverse_code=noop_reverse,
        ),
    ]
