# Generated by Hermes Agent for questionnaire hierarchy metadata.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0020_backfill_workflow_template_role_mapping_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestion",
            name="hierarchy",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Ordered display hierarchy for large questionnaires, e.g. "
                    "Bettercoal Principle → Category → Provision, EO100 Principle → Objective → PT, "
                    "or CGWG Section → Question. Items use {level, code, label}."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="assessmentquestion",
            name="performance_target_level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "PT1 - Minimum Compliance"),
                    (2, "PT2 - Good Practice"),
                    (3, "PT3 - Best Practice"),
                ],
                default=None,
                help_text="EO100 performance target level; blank for non-EO100 questions",
                null=True,
            ),
        ),
    ]
