# Generated by Hermes Agent to repair dev DBs where 0021 was applied
# but assessment_questions.performance_target_level remained NOT NULL.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0021_assessmentquestion_hierarchy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentquestion",
            name="performance_target_level",
            field=models.IntegerField(
                null=True,
                blank=True,
                default=None,
                choices=[
                    (1, "PT1 - Minimum Compliance"),
                    (2, "PT2 - Good Practice"),
                    (3, "PT3 - Best Practice"),
                ],
                help_text="EO100 performance target level; blank for non-EO100 questions",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE assessment_questions "
                "ALTER COLUMN performance_target_level DROP NOT NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
