# Generated by Django 5.1.5 on 2026-05-20 09:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0023_dedupe_assessment_responses_unique_question"),
        ("organizations", "0007_organizationsettings_organizationterminology_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentresponse",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not Checked"),
                    ("needs_answer", "Needs Answer"),
                    ("needs_evidence", "Needs Evidence"),
                    ("evidence_processing", "Evidence Processing"),
                    ("supported", "Supported"),
                    ("partially_supported", "Partially Supported"),
                    ("unsupported", "Unsupported"),
                    ("contradictory", "Contradictory"),
                    ("reviewer_override", "Reviewer Override"),
                    ("pending", "Pending"),
                    ("validated", "Validated"),
                    ("flagged", "Flagged"),
                    ("insufficient_evidence", "Insufficient Evidence"),
                ],
                default="not_checked",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EvidenceCheckRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("result_json", models.JSONField(default=dict)),
                (
                    "model_provider",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("retrieved_evidence_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_check_runs",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_check_runs",
                        to="assessments.framework",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_check_runs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_check_runs",
                        to="assessments.assessmentresponse",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_check_runs",
                        to="assessments.site",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_evidence_check_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evidence_check_runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["response", "-created_at"],
                        name="evidence_ch_respons_1bf720_idx",
                    ),
                    models.Index(
                        fields=["assessment", "status"],
                        name="evidence_ch_assessm_fca5e5_idx",
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="evidence_ch_organiz_6707bf_idx",
                    ),
                ],
            },
        ),
    ]
