# Generated by Django 5.1.5 on 2026-04-06 11:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(default="", max_length=300)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("COORDINATOR", "Coordinator"),
                            ("OPERATOR", "Operator"),
                            ("EXECUTIVE", "Executive"),
                            ("ASSESSOR", "Assessor"),
                            ("CONSULTANT", "Consultant"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["email"],
            },
        ),
    ]
