# Generated by Django 5.1.5 on 2026-04-06 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead Assessor"),
                            ("SENIOR", "Senior Assessor"),
                            ("JUNIOR", "Junior Assessor"),
                            ("EXPERT", "Subject Matter Expert"),
                        ],
                        default="JUNIOR",
                        max_length=20,
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        default=list,
                        help_text="Industry specializations [COAL, OIL_GAS, etc.]",
                    ),
                ),
                ("can_be_lead_assessor", models.BooleanField(default=False)),
                ("biography", models.TextField(blank=True, default="")),
                (
                    "direct_phone_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("timezone", models.CharField(default="UTC", max_length=63)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("region", models.CharField(blank=True, default="", max_length=255)),
                (
                    "current_organisation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_registration_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assessor_profiles",
            },
        ),
    ]
