# Generated by Django 5.1.5 on 2026-04-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_assessorprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
