# Generated by Django 5.1.5 on 2026-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_organization_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="direct_phone_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="AssessorProfile",
        ),
    ]
